name: intake-rolling-zarr
channels:
  - intake
  - informaticslab
  - defaults
dependencies:
  - python=3.6
  - intake
  - intake-rolling-zarr
  - pip:
    - sphinx
    - sphinx-rtd-theme
    - numpydoc
